services:
  # A web service for the API
  - type: web
    name: crypto-rebalancer-api
    env: node
    buildCommand: npm install
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        sync: false # Prompt for this during setup
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-rebalancer-db
          property: connectionString
      - key: CORS_ORIGINS
        value: "https://your-netlify-site-url.netlify.app" # Replace with your actual Netlify URL
      - key: API_KEY
        sync: false # Prompt for this during setup (3commas API key)
      - key: API_SECRET
        sync: false # Prompt for this during setup (3commas API secret)
        
  # A worker service for the trading bot
  - type: worker
    name: crypto-rebalancer-bot
    env: node
    buildCommand: npm install
    startCommand: node src/scripts/runBot.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-rebalancer-db
          property: connectionString
      - key: API_KEY
        sync: false # Prompt for this during setup (3commas API key)
      - key: API_SECRET
        sync: false # Prompt for this during setup (3commas API secret)

databases:
  - name: crypto-rebalancer-db
    plan: free
    databaseName: crypto_rebalancer
    user: crypto_rebalancer_user
